import { z } from 'zod';

export const DenyReason = Object.freeze({
    NETWORK_DISABLED: 'NETWORK_DISABLED',
    WORKSPACE_WRITE_FORBIDDEN: 'WORKSPACE_WRITE_FORBIDDEN',
    HOST_EXEC_FORBIDDEN: 'HOST_EXEC_FORBIDDEN',
    SECRETS_FORBIDDEN: 'SECRETS_FORBIDDEN',
    SKILL_NOT_WHITELISTED: 'SKILL_NOT_WHITELISTED',
    // 控制面拒绝原因
    TASK_WRONG_STATE: 'TASK_WRONG_STATE',
    LEASE_REQUIRED: 'LEASE_REQUIRED',
    LOCK_HELD_BY_OTHER: 'LOCK_HELD_BY_OTHER',
    // 角色工具白名单拒绝
    TOOL_NOT_ALLOWED: 'TOOL_NOT_ALLOWED',
});

export const DenyReasonSchema = z.enum(Object.values(DenyReason));

